import type {Metadata} from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
  const isDarkMatchMedia = window.matchMedia('(prefers-color-scheme: dark)')
  function loadColorScheme() {
    let colorScheme = localStorage.getItem('color-scheme')
    if (colorScheme !== 'dark' && colorScheme !== 'light') {
      colorScheme = isDarkMatchMedia.matches ? 'dark' : 'light'
    }
    document.documentElement.dataset['theme'] = colorScheme
  }

  isDarkMatchMedia.addEventListener('change', loadColorScheme)
  loadColorScheme()
})()`,
          }}
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  )
}
